### ISSUE TITLE
LuaRT installer don't execute

### ISSUE THREAD

**Issue by tellts** [samyeyo/LuaRT#47]
I click on the file to start the installation, but it doesn't work. I installed x86.

**Comment by samyeyo** [comment]
Hi tellts,

I have tested installation for x86 and x64 on both Windows 10 and Windows 11.
It might be related to your antivirus software or SmartScreen protection (for unknown executables).

**Comment by tellts** [comment]
What should I do in such a situation?

**Comment by samyeyo** [comment]
### 🔹Windows operating system prevents the applications from starting
LuaRT may be blocked by Microsoft Defender SmartScreen because executable is not EV certified (executables are not signed). 
➡️If the blue window opens when running setup file, click on **More info** and then **Run anyway**

### 🔹After downloading, Windows Defender places the application in quarantine
During virus scanning, Microsoft Defender may show a false positive result for LuaRT, since the setup executable is signed with an EV certificate.
➡️Open Windows Defender
➡️Click on **Virus & Threat Protection**, select **All recent items*, then select **Allow** from the actions drop-down menu.

**Comment by badiku** [comment]
nowadays, all antivirus software, like symantec or microsoft defender,  tend to mark any unknown .exe files as virus, and delete them immediately.  I think I can make an AV software myself, using such simple method.

or you can give money to these antivirus software to beg them to add your file to white list for a survival 


I just don't use any stupid antivirus software.

**Comment by KikyTokamuro** [comment]
The same problem appears, when you run the installer, nothing happens at all. Tried disabling Windows Defender, didn't help.
Version: Windows 10 Pro (22H2)
LuaRT: v1.4.0

**Comment by samyeyo** [comment]
Sorry for that. What is your CPU ? Des it concern x64 version ?

**Comment by KikyTokamuro** [comment]
Intel(R) Core(TM) i7 CPU 860 @ 2.80GHz
Yes, this applies to the x64 version.

**Comment by samyeyo** [comment]
Ok I've found the reason why the installer crashes...
Latest LuaRT version is compiled with AVX2 instruction set, which your CPU don't support. 
Sorry for that, it will be fixed in next LuaRT version 👍🏻

**Comment by KikyTokamuro** [comment]
Thank you very much, I'll be waiting for the next release!

**Comment by samyeyo** [comment]
A bug is affecting LuaRT installer that prevent to launch it if a previous LuaRT installation is found. For now, just remove the previous installation before LuaRT 1.5.0 installation.

**Comment by KikyTokamuro** [comment]
LuaRT version 1.5.0 fixed my bug, now everything runs fine. Thanks for the new release!
